'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {createContext,useContext,useEffect,useState,type ReactNode,type Dispatch,type SetStateAction} from 'react';
import {initialCase,restoreCase,type CaseState,display,type Scalar} from '../../src/lib/lab';

type CaseContext = {state:CaseState;setState:Dispatch<SetStateAction<CaseState>>;ready:boolean};
const Context=createContext<CaseContext|null>(null);
export function CaseProvider({children}:{children:ReactNode}) {
 const [state,setState]=useState<CaseState>(initialCase);const [ready,setReady]=useState(false);
 useEffect(()=>{try {const raw=localStorage.getItem('bugproof-case-v2');if(raw){const saved=restoreCase(JSON.parse(raw));if(saved)setState(saved);}}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('bugproof-case-v2',JSON.stringify(state));}catch{}},[state,ready]);
 return <Context.Provider value={{state,setState,ready}}>{children}</Context.Provider>;
}
export function useCase(){const ctx=useContext(Context);if(!ctx)throw new Error('CaseProvider missing');return ctx;}
export function Icon({name='arrow',size=20}:{name?:string;size?:number}) {
 const paths:Record<string,ReactNode>={arrow:<><path d="M4 12h16M14 6l6 6-6 6"/></>,check:<path d="m5 12 4 4L19 6"/>,play:<path d="m8 4 12 8-12 8Z"/>,bug:<><rect x="7" y="7" width="10" height="14" rx="5"/><path d="m9 7-2-4m8 4 2-4M3 10h4m10 0h4M3 16h4m10 0h4M12 8v12"/></>,box:<><path d="m12 3 9 5v9l-9 5-9-5V8Z M3 8l9 5 9-5M12 13v9M7.5 5.5l9 5"/></>,code:<><path d="m8 5-6 7 6 7m8-14 6 7-6 7m-3-16-2 18"/></>,shield:<><path d="m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6Z"/><path d="m7 12 3 3 6-6"/></>,book:<><path d="M12 5v16M12 5C7 1 2 3 2 3v16s5-2 10 2c5-4 10-2 10-2V3s-5-2-10 2Z"/></>,reset:<><path d="M3 11a9 9 0 1 1 2 7M3 3v8h8"/></>,download:<><path d="M12 2v14m-5-5 5 5 5-5M3 17v5h18v-5"/></>,copy:<><rect x="8" y="8" width="13" height="13" rx="2"/><path d="M16 8V3H3v13h5"/></>,spark:<path d="m12 1 3 8 8 3-8 3-3 8-3-8-8-3 8-3Z"/>,clock:<><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 3"/></>,close:<path d="m5 5 14 14M5 19 19 5"/>,external:<><path d="M14 3h7v7m0-7L10 14M10 3H3v18h18v-7"/></>};
 return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.arrow}</svg>;
}
export function Bug({mood='happy',className=''}:{mood?:'happy'|'oops'|'sleep';className?:string}) {return <svg className={`bug-mascot ${className}`} viewBox="0 0 180 180" fill="none" aria-hidden="true"><ellipse cx="90" cy="159" rx="44" ry="9" fill="#061d22" opacity=".15"/><g stroke="#102c32" strokeWidth="8" strokeLinecap="round"><path d="m53 76-24-9m26 38-30 10m100-39 26-10m-23 38 28 11M73 45 59 22m49 23 14-25"/></g><rect x="44" y="37" width="92" height="115" rx="44" fill={mood==='oops'?'#fc9577':'#c3f474'} stroke="#102c32" strokeWidth="4"/><path d="M90 95v53" stroke="#102c32" strokeWidth="3"/><circle cx="70" cy="71" r="15" fill="#fffdf4"/><circle cx="110" cy="71" r="15" fill="#fffdf4"/>{mood==='sleep'?<path d="M61 71h18m22 0h18" stroke="#102c32" strokeWidth="4"/>:<><circle cx="74" cy="72" r="5" fill="#102c32"/><circle cx="106" cy="72" r="5" fill="#102c32"/></>}{mood==='oops'?<ellipse cx="90" cy="94" rx="6" ry="8" fill="#102c32"/>:<path d="M79 93q11 13 22 0" stroke="#102c32" strokeWidth="3" strokeLinecap="round"/>}</svg>}
export function Shell({children}:{children:ReactNode}){const pathname=usePathname();return <><a className="skip" href="#main">Skip to content</a><header className="site-header"><Link href="/" className="brand"><span className="brand-mark"><Icon name="bug" size={23}/></span>bugproof<span className="brand-dot">.</span></Link><nav aria-label="Main navigation"><Link className={pathname==='/workbench'?'active':''} href="/workbench">Workbench</Link><Link className={pathname==='/missions'||pathname.startsWith('/lab')?'active':''} href="/missions">The lab</Link><Link className={pathname==='/evidence'?'active':''} href="/evidence">Evidence vault</Link><Link className={pathname==='/guide'?'active':''} href="/guide">How it works</Link></nav><Link className="header-action" href="/workbench">Build a test<Icon size={16}/></Link></header><main id="main">{children}</main><footer className="site-footer"><Link href="/" className="brand">bugproof.</Link><span>From failure to test to verified repair.</span><div><span className="live-dot"/> Built with IBM Bob <a href="https://github.com/EarlPly/bugproof" target="_blank" rel="noreferrer">Source <Icon name="external" size={13}/></a></div></footer></>}
const steps=[['report','The report'],['replay','Catch the bug'],['repair','Inspect the fix'],['verify','Prove it']];
export function LabLayout({step,children}:{step:string;children:ReactNode}) {const {state}=useCase();const idx=steps.findIndex(x=>x[0]===step);return <div className="lab-shell"><div className="lab-top"><Link href="/missions" className="back-link">← Mission library</Link><span className="mono">CASE {state.missionId==='negative'?'02':state.missionId==='text'?'03':'01'} / INVENTORY SERVICE</span><span className="subtle">Controlled sample · reset each request</span></div><nav className="step-nav" aria-label="Investigation steps">{steps.map(([slug,label],i)=><Link key={slug} href={`/lab/${slug}`} className={`${i===idx?'current':''} ${i<idx?'past':''}`} aria-current={i===idx?'step':undefined}><span>{i<idx?<Icon name="check" size={16}/>:String(i+1).padStart(2,'0')}</span>{label}<Icon size={16}/></Link>)}</nav><div className="lab-content" key={step}>{children}</div></div>}
export function Intro({eyebrow,title,emphasis,description}:{eyebrow:string;title:string;emphasis:string;description:string}) {return <div className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title} <em>{emphasis}</em></h1><p className="lede">{description}</p></div>}
export function Coach({title,children,mood='happy'}:{title:string;children:ReactNode;mood?:'happy'|'oops'|'sleep'}){return <aside className="coach"><Bug mood={mood}/><div><p className="eyebrow">A NOTE FROM THE LAB</p><h3>{title}</h3><p>{children}</p></div></aside>}
export function Locked({step='report',text='Write your report to start this investigation.'}:{step?:string;text?:string}) {return <div className="locked"><Bug mood="sleep"/><h2>One clue at a time.</h2><p>{text}</p><Link className="button primary" href={`/lab/${step}`}>Continue investigation <Icon/></Link></div>}
export function Shelf({stock=5,bad=false}:{stock?:Scalar;bad?:boolean}) {const n=typeof stock==='number'&&Number.isFinite(stock)?Math.max(0,Math.min(7,Math.floor(stock))):0;return <div className={`shelf ${bad?'shelf-bad':''}`} aria-label={`${display(stock)} units remaining`}><div className="shelf-boxes">{Array.from({length:5},(_,i)=><span key={i} className={`inventory-box ${i<n?'filled':'empty'}`} style={{animationDelay:`${i*65}ms`}}><Icon name="box" size={30}/></span>)}{typeof stock==='number'&&stock>5&&<span className="extra-stock">+{stock-5}</span>}{bad&&<span className="shelf-alert">!</span>}</div><div className="shelf-plank"/><div className="shelf-label">DEMO-001 <span>THE STOCK ROOM</span></div></div>}
export function ErrorNote({message}:{message:string}){return message?<p className="error-note" role="alert">{message}</p>:null;}
export function DownloadButton({value,name,label='Download report'}:{value:unknown;name:string;label?:string}) {return <button className="button secondary" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Icon name="download" size={18}/>{label}</button>}
export function CopyButton({text,label='Copy'}:{text:string;label?:string}){const [copied,setCopied]=useState(false);const [fallback,setFallback]=useState(false);return <><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setFallback(true);}}}><Icon name={copied?'check':'copy'} size={18}/>{copied?'Copied!':label}</button>{fallback&&<label className="copy-fallback">Select and copy this text<textarea readOnly value={text} onFocus={e=>e.target.select()}/></label>}</>}
