'use client';
import Link from 'next/link';
import {useState,type FormEvent} from 'react';
import {Icon,Intro,CopyButton,DownloadButton,useCase} from './core';
import {parseQuantity} from '../../src/lib/lab';
import {parseJson,validateDraft,compare,vitestSnippet,bobTask,issueText,type Draft,type Difference} from '../../src/lib/workbench';

type Form = {title:string;path:string;method:Draft['method'];request:string;expectedStatus:string;expectedBody:string;actualStatus:string;actualBody:string};
const starting:Form={title:'',path:'/api/orders',method:'POST',request:'{\n  "quantity": 7\n}',expectedStatus:'409',expectedBody:'{\n  "message": "insufficient stock"\n}',actualStatus:'200',actualBody:'{\n  "message": "reserved"\n}'};
function read(form:Form):Draft {
  const draft:Draft={title:form.title,path:form.path,method:form.method,request:form.request.trim()?parseJson(form.request,'Request body'):undefined,expectedStatus:Number(form.expectedStatus),expectedBody:parseJson(form.expectedBody,'Expected response'),actualStatus:Number(form.actualStatus),actualBody:parseJson(form.actualBody,'Observed response')};
  validateDraft(draft);return draft;
}
export function Workbench(){
 const {state}=useCase();
 const [form,setForm]=useState<Form>(starting),[result,setResult]=useState<{draft:Draft;differences:Difference[]}|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 function update<K extends keyof Form>(key:K,value:Form[K]){setForm(v=>({...v,[key]:value}));setResult(null);setError('');}
 function analyze(e:FormEvent){e.preventDefault();try{const draft=read(form);setResult({draft,differences:compare(draft)});setError('');}catch(e){setError((e as Error).message);setResult(null);}}
 async function sample(){setLoading(true);setError('');try{
   const observed=await fetch('/api/reserve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'original',quantity:7})});
   const actualBody=await observed.json();
   const expectedBody={status:409,stock:5,reserved:0,message:'insufficient stock'};
   const next:Form={title:'Seven-item reservation oversells stock',path:'/api/reserve',method:'POST',request:'{\n  "mode": "original",\n  "quantity": 7\n}',expectedStatus:'409',expectedBody:JSON.stringify(expectedBody,null,2),actualStatus:String(observed.status),actualBody:JSON.stringify(actualBody,null,2)};
   setForm(next);const draft=read(next);setResult({draft,differences:compare(draft)});
 }catch{setError('The live BugProof example could not be loaded. Try again or enter your own sanitized example.');}finally{setLoading(false);}}
 function fromLab(){if(!state.original||!state.fixed)return;const next:Form={title:state.title||'Inventory reservation response',path:'/api/reserve',method:'POST',request:JSON.stringify({mode:'original',quantity:parseQuantity(state.rawQuantity)},null,2),expectedStatus:String(state.fixed.status),expectedBody:JSON.stringify(state.fixed,null,2),actualStatus:String(state.original.status),actualBody:JSON.stringify(state.original,null,2)};setForm(next);const draft=read(next);setResult({draft,differences:compare(draft)});setError('');}
 const test=result?vitestSnippet(result.draft):'',task=result?bobTask(result.draft):'',issue=result?issueText(result.draft,result.differences):'';
 return <div className="wrap page workbench-page"><div className="workbench-intro"><Intro eyebrow="THE DEVELOPER WORKBENCH" title="Bring a failing response." emphasis="Leave with a test." description="Paste a redacted API example. BugProof compares expected and observed JSON, writes a regression test, and prepares a focused task for IBM Bob. Your pasted values stay in this tab."/><div className="workbench-intro-actions"><button className="button primary" type="button" disabled={loading} onClick={sample}>{loading?'Running sample…':'Load the live BugProof failure'}<Icon name="play" size={17}/></button>{state.original&&state.fixed&&<button className="button secondary" type="button" onClick={fromLab}>Use my lab result <Icon name="external" size={16}/></button>}<Link className="text-link" href="/guide">How to use it <Icon size={16}/></Link></div></div>
 <form onSubmit={analyze} className="workbench-form panel"><div className="workbench-section-head"><span className="workbench-number">01</span><div><h2>Describe the failing call</h2><p>Use a redacted API example. This tool does not send your pasted values to our server.</p></div></div><div className="workbench-fields"><label className="span-2">Case title<input required maxLength={100} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. Reservation accepts more items than exist"/></label><label>Method<select value={form.method} onChange={e=>update('method',e.target.value as Form['method'])}>{['GET','POST','PUT','PATCH','DELETE'].map(v=><option key={v}>{v}</option>)}</select></label><label>Endpoint path<input required maxLength={300} value={form.path} onChange={e=>update('path',e.target.value)} placeholder="/api/orders"/></label><label className="span-2">Request body · JSON, optional<textarea className="mono" rows={5} spellCheck={false} value={form.request} onChange={e=>update('request',e.target.value)} placeholder={'{\n  "quantity": 7\n}'}/></label></div><div className="workbench-responses"><div className="workbench-response"><span className="tag mint">EXPECTED CONTRACT</span><label>HTTP status<input inputMode="numeric" value={form.expectedStatus} onChange={e=>update('expectedStatus',e.target.value)}/></label><label>Response JSON<textarea className="mono" rows={9} spellCheck={false} value={form.expectedBody} onChange={e=>update('expectedBody',e.target.value)}/></label></div><div className="workbench-response"><span className="tag coral">OBSERVED FAILURE</span><label>HTTP status<input inputMode="numeric" value={form.actualStatus} onChange={e=>update('actualStatus',e.target.value)}/></label><label>Response JSON<textarea className="mono" rows={9} spellCheck={false} value={form.actualBody} onChange={e=>update('actualBody',e.target.value)}/></label></div></div>{error&&<p className="error-note" role="alert">{error}</p>}<div className="workbench-submit"><p><Icon name="shield" size={18}/> Comparison and files are created locally in your browser.</p><button className="button primary" type="submit">Build the developer handoff <Icon/></button></div></form>
 {result&&<section className="workbench-output" aria-live="polite"><div className="workbench-section-head"><span className="workbench-number">02</span><div><h2>{result.differences.length?`${result.differences.length} difference${result.differences.length===1?'':'s'} found`:'No difference in the supplied responses'}</h2><p>{result.differences.length?'These are the exact values to preserve in a regression test.':'Check the example or add an assertion before calling this a bug.'}</p></div></div>{result.differences.length>0&&<div className="difference-list panel"><div><strong>WHERE</strong><strong>EXPECTED</strong><strong>OBSERVED</strong></div>{result.differences.map((d,i)=><div key={`${d.path}-${i}`}><code>{d.path}</code><code>{d.expected}</code><code>{d.actual}</code></div>)}</div>}<div className="workbench-artifacts"><article className="panel"><span className="tag mint">READY TO RUN</span><h3>Vitest regression test</h3><p>Paste into your repository, set <code>BASE_URL</code>, then run it before and after the fix. Adjust the expected response if the contract is only partial.</p><pre>{test}</pre><CopyButton text={test} label="Copy test"/></article><article className="panel"><span className="tag lilac">READY FOR IBM BOB</span><h3>A focused Bob task</h3><p>Open your authorized repository in IBM Bob IDE and give Bob this task and the regression test. Bob does the investigation there, with your review.</p><pre>{task}</pre><CopyButton text={`${task}\nRegression test:\n${test}`} label="Copy Bob handoff"/></article><article className="panel"><span className="tag coral">READY TO FILE</span><h3>Issue summary</h3><p>Share the expected and observed values with a teammate. Check the generated summary before creating an issue.</p><pre>{issue}</pre><CopyButton text={issue} label="Copy issue"/></article></div><div className="workbench-export"><DownloadButton value={{case:result.draft,differences:result.differences,vitest:test,bobTask:task,issue}} name="bugproof-developer-handoff.json" label="Download full handoff"/><Link href="/missions" className="text-link">Explore the working demo <Icon size={17}/></Link></div></section>}
 <div className="workbench-footer-note"><strong>What this workbench does:</strong> compares the example you provide and creates editable developer artifacts. It does not call an external API, inspect your repository, or run IBM Bob from this page. The <Link href="/missions">guided lab</Link> shows the complete workflow on a sample service.</div></div>;
}
